//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Yakovenko.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int id_Direction { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
