//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Yakovenko.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public System.DateTime Date_event { get; set; }
        public decimal Mark { get; set; }
        public int id_Group { get; set; }
        public string Name { get; set; }
        public int id { get; set; }
    }
}
